name: Docker Image Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for scanning
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: controlit-scan:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: 'controlit-scan'
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        exit-code: 0
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'

    - name: Run Dockle security check
      uses: goodwithtech/dockle-action@v1
      with:
        image: 'controlit-scan'
        format: 'sarif'
        output: 'dockle-results.sarif'
        exit-code: 0
        exit-level: 'INFO'

    - name: Upload Dockle results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'dockle-results.sarif'
      continue-on-error: true